### ISSUE TITLE
Appears not to be fully compatible with fastboot.

### ISSUE THREAD

**Issue by alexmasita** [rmmmp/ember-cloud-firestore-adapter#37]
@rmmmp , I have hit the following issue:
```
TypeError: _this4.get(...).firestore is not a function
    at /Users/alexmasita/External/Personal/projects/Ember-Apps/mobile-services/tmp/broccoli_persistent_filterautoprefixer_filter-output_path-xEKeiDYd.tmp/assets/addon-tree-output/ember-cloud-firestore-adapter/adapters/cloud-firestore.js:161:1
    at initializePromise (/Users/alexmasita/External/Personal/projects/Ember-Apps/mobile-services/tmp/broccoli_persistent_filterautoprefixer_filter-output_path-xEKeiDYd.tmp/assets/rsvp.js:418:1)
   ........There is more code below this truncated for brevity..........
```
This issue disappears when I put the following code in my route:

```
model() {
    if (get(this, 'fastboot.isFastBoot')) return;
    return get(this, 'store').findAll('vehicle');
}
```
It means their needs to be a fastboot check somewhere in the adapter that negates the need for this check.  What do you think?

**Comment by rmmmp** [comment]
The idea is to keep this adapter from working even in fastboot so we shouldn't be doing that check.

I may have an idea on why it doesn't work in fastboot. It might be because Firestore isn't part of the Firebase module and I was only able to whitelist Firebase in fastboot as instructed [here](https://www.ember-fastboot.com/docs/addon-author-guide#requiring-node-modules). I may need to add a `firebase/firestore` in that `fastbootDependencies`.
